import {
  DashboardOutlined,
  SnippetsOutlined,
  DotChartOutlined,
  FundOutlined,
  ToolOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const dashBoardNavTree = [
  {
    key: "",
    path: `${APP_PREFIX_PATH}`,
    title: "sidenav.dashboard",
    icon: DashboardOutlined,
    breadcrumb: false,
    submenu: [
      {
        key: "dashboards-default",
        path: `${APP_PREFIX_PATH}/home`,
        title: "sidenav.dashboard.default",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "dashboards-analytic",
        // path: `${APP_PREFIX_PATH}`,
        title: "Tools",
        icon: ToolOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "change-password",
            path: `${APP_PREFIX_PATH}/change-password`,
            title: "Change Password",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "block-vendor",
            path: `${APP_PREFIX_PATH}/block-vendor`,
            title: "Block Vendor",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "unblock-vendor",
            path: `${APP_PREFIX_PATH}/unblock-vendor`,
            title: "Unblock Vendor",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "master",
        path: `${APP_PREFIX_PATH}/master`,
        title: "Master",
        icon: SnippetsOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "vendor-master",
            path: `${APP_PREFIX_PATH}/vendor-master`,
            title: "Vendor Master",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "employee-master",
            path: `${APP_PREFIX_PATH}/employee-master`,
            title: "Employee Master",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "valley-allocation",
            path: `${APP_PREFIX_PATH}/valley-allocation`,
            title: "Valley Allocation",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "category-master",
            path: `${APP_PREFIX_PATH}/category-master`,
            title: "Category Master",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "sub-category-master",
            path: `${APP_PREFIX_PATH}/sub-category-master`,
            title: "Sub Category Master",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "item-master",
            path: `${APP_PREFIX_PATH}/item-master`,
            title: "Item Master",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "leave-allocation",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "Leave Allocation",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "vendor",
            path: `${APP_PREFIX_PATH}/vendor`,
            title: "Vendor",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "pay-out",
            path: `${APP_PREFIX_PATH}/pay-out`,
            title: "Pay Out",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "day-work-out",
        path: `${APP_PREFIX_PATH}/master`,
        title: "Day Work Out",
        icon: FundOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "order-list",
            path: `${APP_PREFIX_PATH}/vendor-master`,
            title: "Order List",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "reject-order-list",
            path: `${APP_PREFIX_PATH}/employee-master`,
            title: "Reject Order List ",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "generate-pay-out",
            path: `${APP_PREFIX_PATH}/valley-allocation`,
            title: "Generate Pay Out",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "customer-complain",
            path: `${APP_PREFIX_PATH}/category-master`,
            title: "Customer Complain",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "resolved-complaints",
            path: `${APP_PREFIX_PATH}/sub-category-master`,
            title: "Resolve Complaints",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "capture-order",
            path: `${APP_PREFIX_PATH}/item-master`,
            title: "Capture Order",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "employee-pay-out",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "Employee Pay Out Allocation",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "report",
        path: `${APP_PREFIX_PATH}/master`,
        title: "Report",
        icon: DotChartOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "vendor-list",
            path: `${APP_PREFIX_PATH}/vendor-master`,
            title: "Vendor List",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "employee-list",
            path: `${APP_PREFIX_PATH}/employee-master`,
            title: "Employee List ",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "attendance-list",
            path: `${APP_PREFIX_PATH}/valley-allocation`,
            title: "Attendance List",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "order-report",
            path: `${APP_PREFIX_PATH}/category-master`,
            title: "Order Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "reject-report",
            path: `${APP_PREFIX_PATH}/sub-category-master`,
            title: "Rejection Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "collection-report",
            path: `${APP_PREFIX_PATH}/item-master`,
            title: "Collection Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "pay-out-report",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "Pay Out Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "gst-report",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "GST Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "tds-report",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "TDS Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "profile-report",
            path: `${APP_PREFIX_PATH}/leave-allocation`,
            title: "Profile Report",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
    ],
  },
];

const navigationConfig = [...dashBoardNavTree];

export default navigationConfig;
